export default [
  {
    value: '',
    type: 'text',
    name: 'last_name',
    placeholder: 'Nom',
    required: true,
  },
  {
    value: '',
    type: 'text',
    name: 'first_name',
    placeholder: 'Prénom',
    required: true,
  },
  {
    value: '',
    type: 'text',
    name: 'pseudo',
    placeholder: 'Pseudo',
    required: true,
  },
  {
    value: '',
    type: 'email',
    name: 'mail',
    placeholder: 'E-Mail',
    required: true,
  },
  {
    value: '',
    type: 'text',
    name: 'address',
    placeholder: 'Adresse',
    required: true,
  },
  {
    value: '',
    type: 'text',
    name: 'zip',
    placeholder: 'Code postal',
    required: true,
  },
  {
    value: '',
    type: 'text',
    name: 'city',
    placeholder: 'Ville',
    required: true,
  },
  {
    value: '',
    type: 'tel',
    pattern: '(\\d{2}\\s){4}\\d{2}',
    name: 'phone',
    placeholder: 'Tél',
    required: true,
  },
  {
    value: '',
    type: 'hidden',
    name: 'role',
    placeholder: 'role',
    required: true,
  },
  {
    value: '',
    type: 'password',
    name: 'password',
    placeholder: 'Mot de passe',
    required: true,
  },
  {
    value: '',
    type: 'password',
    name: 'password2',
    placeholder: 'Confirmation mot de passe',
    required: true,
  },
];
